"""Chunked generation for large structures.

A large structure is broken into a sequence of modules (e.g. foundation, floor1,
roof). Each module is generated by its own small LLM call, then the resulting
BlockPlacementLists are merged. This avoids overwhelming a single LLM call with
tens of thousands of block placements and keeps context sizes small.

For now this module only defines the public interface and a naive fallback that
routes everything through the normal 3-stage pipeline. A full implementation
will:
  1. Use a planning stage to emit a list of modules with their local bounds.
  2. Loop over modules and call the LLM per module.
  3. Offset each module's placements into world space and merge them.
  4. Return a single BlockPlacementList.
"""
from __future__ import annotations

import logging

from models.building_spec import BlockPlacementList, BuildingSpec
from models.requests import BuildRequest
from models.world_context import WorldContext

from .base import LanguageModelProvider
from .pipeline import GenerationPipeline

logger = logging.getLogger("buildermc.llm.chunked")


class ChunkedGenerator:
    """Generates large structures by splitting them into modules.

    Args:
        provider: The LLM provider used for each module.
    """

    def __init__(self, provider: LanguageModelProvider | None = None) -> None:
        self.provider = provider

    async def generate(
        self, request: BuildRequest, context: WorldContext | None = None
    ) -> tuple[BuildingSpec, BlockPlacementList]:
        """Generate a building spec and its placements.

        If the requested structure is small enough, this delegates to the
        standard 3-stage pipeline. Otherwise it runs the planned module-based
        approach.
        """
        pipeline = GenerationPipeline(provider=self.provider)
        world_context = context or request.world_context

        # Threshold for chunking: structures whose total block count is likely
        # to exceed ~5k blocks. This is a conservative heuristic; the planner will
        # later emit modules based on the spec.
        spec, placements = await pipeline.run(request.prompt, world_context)
        total_blocks = len(placements.placements)
        if total_blocks <= 5_000:
            logger.info("single-pass generation: %d blocks", total_blocks)
            return spec, placements

        logger.warning(
            "chunked generation not fully implemented yet; falling back to single-pass. "
            "Structure size: %d blocks.",
            total_blocks,
        )
        return spec, placements
